### ISSUE TITLE
Since the upgrade to 21.1 this stops working

### ISSUE THREAD

**Issue by soothill** [donpdonp/dashj#1]
Since the upgrade to 21.1 version of storj this script has stopped working :- 

version : 0.21.1 (latest)

jq: error (at <stdin>:1): null (null) and number (1024) cannot be divided
jq: error (at <stdin>:1): null (null) and number (1024) cannot be divided
bandwidth avail: 25000.000GB used: 11049.088GB  ingress:  0.0MB  egress:  0.0MB
     disk avail: 15000.000GB used: 2475.809GB

sat-id audits    score    uptime    score    storageDay atRest     bndwdthDay egress    ingress
{      0   /0    0.000000    0/0    0.000000               0.000MB              0.000MB   0.000MB
./dashj.sh: line 21: printf: null: invalid number
./dashj.sh: line 21: printf: null: invalid number
./dashj.sh: line 21: printf: null: invalid number
./dashj.sh: line 21: printf: null: invalid number
./dashj.sh: line 21: printf: null: invalid number

**Comment by donpdonp** [comment]
thanks for the notice. just pushed fixes for 0.21.1. note that each satellite now has a total storage and total bandwidth so I took out the 'last day' logic and put those in place.

**Comment by donpdonp** [comment]
also note the output isnt making total sense. i'm seeing 16GB of "used" disk space and the satellites report disk space used of 0gb, 0gb, 0gb, and 628Gb. it is what is in the json.

**Comment by donpdonp** [comment]
just restored the "last day" stats to the dashboard
